/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1b1b",
        "secondary-container": "#e2dfde",
        "on-tertiary-container": "#f3fffd",
        "primary": "#994127",
        "surface-variant": "#e5e2e1",
        "outline": "#89726c",
        "surface-tint": "#9c4329",
        "primary-fixed-dim": "#ffb5a0",
        "error": "#ba1a1a",
        "background": "#fcf9f8",
        "surface-container-highest": "#e5e2e1",
        "surface": "#fcf9f8",
        "on-primary-fixed-variant": "#7d2c14",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "on-surface": "#1c1b1b",
        "primary-container": "#b8583d",
        "on-primary-fixed": "#3b0900",
        "on-error-container": "#93000a",
        "surface-container-high": "#eae7e7",
        "surface-bright": "#fcf9f8",
        "tertiary-fixed-dim": "#70d7d0",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#dcc1ba",
        "on-primary-container": "#fffbff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed-variant": "#00504c",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container": "#f0eded",
        "primary-fixed": "#ffdbd1",
        "secondary": "#5f5e5e",
        "inverse-primary": "#ffb5a0",
        "tertiary-fixed": "#8df4ec",
        "surface-dim": "#dcd9d9",
        "on-tertiary-fixed": "#00201e",
        "tertiary": "#006763",
        "on-surface-variant": "#56423d",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#313030",
        "on-error": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-container": "#636262",
        "tertiary-container": "#00837d",
        "inverse-on-surface": "#f3f0ef",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
